### ISSUE TITLE
Bug: Stats flag doesn't output anything extra with multiple Config

### ISSUE THREAD

**Issue by aman29271** [webpack/webpack-cli#1475] opened 2020-04-17 14:52 UTC
**Describe the bug**

**What is the current behavior?**
Using `--stats verbose` or `--verbose` . It should output everything from stats.

```bash
~/Desktop/test$ npx webpack-cli --stats verbose
Hash: 05ba6d353504bf32ca88
Version: webpack 4.42.1
Child
    Hash: 05ba6d353504bf32ca88
    Time: 97ms
    Built at: 17/04/2020 8:18:14 pm
             Asset       Size  Chunks             Chunk Names
    test-bundle.js  967 bytes       0  [emitted]  main
    Entrypoint main = test-bundle.js
    [0] ./test.js 70 bytes {0} [built]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```
**To Reproduce**

1. Use `--stats verbose` or `--verbose` flag 

**Expected behavior**
```bash
~/Desktop/test$ npx webpack-cli --stats verbose
Hash: 05ba6d353504bf32ca88
Version: webpack 4.42.1
Child
    Hash: 05ba6d353504bf32ca88
    Time: 101ms
    Built at: 17/04/2020 8:21:16 pm
             Asset       Size  Chunks             Chunk Names
    test-bundle.js  967 bytes       0  [emitted]  main
    Entrypoint main = test-bundle.js
    chunk    {0} test-bundle.js (main) 70 bytes [entry] [rendered]
        > /home/phoenix/Desktop/test/test.js main
     [0] ./test.js 70 bytes {0} [depth 0] [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry /home/phoenix/Desktop/test/test.js  main
    
    LOG from webpack.buildChunkGraph.visitModules
    <t> prepare: 0.460218ms
    <t> visiting: 0.166156ms
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by evilebottnawi** [comment] 2020-04-17 15:02
Can't reproduce

**Comment by anshumanv** [comment] 2020-04-17 15:04
@aman29271 use next branch

**Comment by aman29271** [comment] 2020-04-17 15:07
looks broken with next. Please verify?

**Comment by anshumanv** [comment] 2020-04-17 15:10
Works fine for me.

**Comment by anshumanv** [comment] 2020-04-17 15:10
![image](https://user-images.githubusercontent.com/21009455/79584156-a446e180-80eb-11ea-9f4c-b6559c55b5d4.png)

**Comment by aman29271** [comment] 2020-04-17 15:11
I forgot. Can you please check with multiple config also?

**Comment by evilebottnawi** [comment] 2020-04-17 15:15
`--stats verbose` should not output everything, it should output everything from stats, in you screenshot you have logger, it is out of scope `--stats` flag

**Comment by aman29271** [comment] 2020-04-17 16:50
Yes, there is some part of logger in stats also. Is it working fine with multiple config also?

**Comment by evilebottnawi** [comment] 2020-04-17 17:09
@aman29271 We should add test for logger output, we should not eat that

**Comment by aman29271** [comment] 2020-04-17 17:42
Yup, we are not the Devil :smile:.    may need help in future...

**Comment by evilebottnawi** [comment] 2020-04-17 17:46
You can send a test to ensure we don't eat that, it will be great

**Comment by aman29271** [comment] 2020-04-17 18:12
Going through code, I haven't find any logger attached. I think that was default by webpack.

**Comment by aman29271** [comment] 2020-04-18 09:02
I haven't added any extra piece of code outside producing this issue. checkout this issue [https://github.com/aman29271/webpack-issue](https://github.com/aman29271/webpack-issue) and let us know if it still persist.

**Comment by evilebottnawi** [comment] 2020-10-03 14:03
I want to close issue, because it is out of scope webpack-cli, verbose is verbose (not `all`), but you can achieve this using https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L3147

**Closed by evilebottnawi** 2020-10-03 14:03 UTC
