### ISSUE TITLE
self.prompt is not a function (webpack-scaffold)

### ISSUE THREAD

**Issue by b0000ring** [webpack/webpack-cli#1401] opened 2020-04-01 14:39 UTC
Hello!
When I try some scaffold examples (like `webpack-cli init webpack-scaffold-vue`)
I get an error 
`TypeError: self.prompt is not a function
    at InputValidate (/usr/local/lib/node_modules/webpack-scaffold-vue/node_modules/@webpack-cli/webpack-scaffold/index.js:104:17)
    at WebpackGenerator.prompting (/usr/local/lib/node_modules/webpack-scaffold-vue/index.js:44:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-scaffold-vue/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/webpack-scaffold-vue/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/webpack-scaffold-vue/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/webpack-scaffold-vue/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)`

My versions is:
"dependencies": {
    "@webpack-cli/init": "0.2.2",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11"
  }

**Comment by evilebottnawi** [comment] 2020-04-01 14:54
It looks like you just deleted our lovely crafted issue template It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by evilebottnawi** 2020-04-01 14:54 UTC

**Comment by b0000ring** [comment] 2020-04-01 15:06
I think no, because if I generate my own scaffold by running `npx webpack-scaffold`, and trying to run `npx webpack-cli init ./scaffold/index.js ` it still the same.
If I comment **prompting** method in generated scaffold this error disappears, but new one `Cannot convert undefined or null to object` appears.
Is I'm doing something wrong?
Because I trying to do that like in a webpack docs.

**Comment by evilebottnawi** [comment] 2020-04-01 15:33
Please format issue using issue template and provide reproducible test repo
