### ISSUE TITLE
Throwing error when installing webpack-cli

### ISSUE THREAD

**Issue by Vasikaran** [webpack/webpack-cli#257] opened 2018-01-30 09:29 UTC
**Do you want to request a *feature* or report a *bug*?**

## I think it's a bug.

**What is the current behavior?**
It's throwing an error when installing. 

**If the current behavior is a bug, please provide the steps to reproduce.**

![image](https://user-images.githubusercontent.com/25631481/35558401-f5597862-05cd-11e8-8091-2e96bbaa6e97.png)

**What is the expected behavior?**

I just want to try Webpack 4.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

OS - Windows 10
Node JS - v8.9.4
NPM - 5.6.0

**Comment by ematipico** [comment] 2018-01-30 12:58
We are working on a fix. Closing as duplicate of #182

**Closed by ematipico** 2018-01-30 12:58 UTC
