### ISSUE TITLE
Serve command not passing webpack `devServer` config to webpack-dev-server

### ISSUE THREAD

**Issue by lewisharveydeveloper** [webpack/webpack-cli#1974] opened 2020-10-21 20:30 UTC
reopening https://github.com/webpack/webpack-cli/issues/1469

here are my dev dependencies: 
```
"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "babel-loader": "^8.1.0",
    "react-hot-loader": "^4.13.0",
    "webpack": "^5.1.3",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
  }
```

my dev server details:

`  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000
  }`

Command: 
`"start": "webpack serve --config ./webpack.config.js --mode development",`

**What is the current behavior?**

```
i ｢wds｣: Project is running at http://localhost:9000/

i ｢wds｣: webpack output is served from undefined

i ｢wds｣: Content not from webpack is served from C:\Users\lehar\scaling-todo-app\dist
```
The first change i make reloads, any after that do not.
The only way i can see updates is by stopping and reserving, even refreshing the page doesn't show updates.

**Steps to reproduce the behavior:**

Define a devServer config in your webpack config file
Run webpack serve --config webpack.dev.js

**Comment by evilebottnawi** [comment] 2020-10-21 20:32
Closing https://github.com/webpack/webpack-cli/issues/1469#issuecomment-698267343

**Comment by evilebottnawi** [comment] 2020-10-21 20:33
No need open an issue without additional information, I can't fix something somewhere

**Comment by lewisharveydeveloper** [comment] 2020-10-21 20:36
> No need to open an issue without additional information, I can't fix something somewhere

@evilebottnawi Sorry i accidentally submitted. Please reopen and see details

**Comment by evilebottnawi** [comment] 2020-10-21 20:38
@lewisharveydeveloper Please create reproducible test repo, can't reproduce locally

**Comment by lewisharveydeveloper** [comment] 2020-10-21 20:39
@evilebottnawi https://github.com/lewisharveydeveloper/scaling-todo-app

**Comment by evilebottnawi** [comment] 2020-10-21 20:45
@lewisharveydeveloper you need to set `target: 'web'`, we are working on fixes

**Comment by lewisharveydeveloper** [comment] 2020-10-21 20:48
@evilebottnawi set target to web and pushed changes to my shared repo. no change

**Comment by evilebottnawi** [comment] 2020-10-21 20:50
You need `hot: true` also

**Comment by lewisharveydeveloper** [comment] 2020-10-21 20:52
Thanks for quick responses, 
set hot to true but no change unfortunately.

**Comment by evilebottnawi** [comment] 2020-10-21 20:53
I will look at the problem tmorrow

**Comment by lewisharveydeveloper** [comment] 2020-10-21 20:53
@evilebottnawi Thank you :)

**Comment by evilebottnawi** [comment] 2020-10-29 15:00
No problems, works fine

**Comment by evilebottnawi** [comment] 2020-10-29 15:01
![Screenshot from 2020-10-29 18-00-59](https://user-images.githubusercontent.com/4567934/97591514-beee0180-1a10-11eb-9b8c-149faa6bc7c7.png)

**Comment by tx-steven** [comment] 2020-10-29 19:40
@evilebottnawi is `target: 'web'` a temporary solution? I'm seeing that this problem might be fixed in #1469 but it doesn't look like those changes are published in a new version yet.

**Comment by lewisharveydeveloper** [comment] 2020-10-29 20:00
@evilebottnawi i made a new folder and pulled my repo.
I ran` npm install`, and then `npm run.` 
I still have the same problem, the first refresh works but no subsequent ones.

**Comment by evilebottnawi** [comment] 2020-10-30 14:18
@tx-steven Yes, ` target: 'web'` is a temporary solution

@lewisharveydeveloper still can't reproduce, all works fine

**Comment by evilebottnawi** [comment] 2020-10-30 14:20
I want to close because I can't reproduce, there is not magic with new `webpack serve`, feel free to feedback

**Closed by evilebottnawi** 2020-10-30 14:20 UTC
Labels: Bug

**Comment by evilebottnawi** [comment] 2020-10-30 14:22
In original repo it doesn't work, because you have resolving problems, so webpack can't init HMR, problems with code === problems with HMR, nothing to do here

**Comment by evilebottnawi** [comment] 2020-10-30 14:22
https://github.com/lewisharveydeveloper/scaling-todo-app/blob/master/src/index.js#L5 - no firebase in mode_modules
