### ISSUE TITLE
Cannot install webpack-cli via npm

### ISSUE THREAD

**Issue by mu88** [webpack/webpack-cli#326] opened 2018-03-09 09:31 UTC
I'm learning JavaScript and would like to use webpack, so I've installed it via `npm install --save-dev webpack` without any problems.  
When executing `node_modules\.bin\webpack webpack.config.js`, it says that I have to install `webpack-cli`, so I ran `npm install webpack-cli -D`. This command takes extremely long for fetching the metadata and fails after approximately one minute with the following error:
`
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ev1stensberg/generator.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection refused
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
`

I'm behind a corporate proxy, for sure, but I've configured the npm proxy settings and fetching other modules is not a problem. Only `webpack-cli` doesn't seem to work.

**Comment by andrewpmontgomery** [comment] 2018-03-09 09:38
Same as bugs #311 #313 #314 #318 etc. All tracked under bug #161 . Hopefully will be fixed with PR #323

**Comment by mu88** [comment] 2018-03-09 09:40
Thanks for your quick reply! So is there any way for me to use webpack via CLI right now? Do I have to install a previous version of webpack which does not rely on webpack-cli?

**Comment by andrewpmontgomery** [comment] 2018-03-09 10:02
Just install webpack-cli 2.0.9 for now.

**Comment by dhruvdutt** [comment] 2018-03-09 13:17
@mu88 You can use `2.0.9` for now but beware of some other issues which were fixed in `2.0.10`. Check the [changelog](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#2010-2018-03-02) to know more.

Also, you can close this issue since we're already tracking it in #161.

**Comment by ematipico** [comment] 2018-03-09 14:17
Duplicate of #161

**Closed by ematipico** 2018-03-09 14:17 UTC
