### ISSUE TITLE
Bug: css bundle file not used / applied

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack-cli#427] opened 2018-05-02 07:36 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The supplied bundle file for CSS is not used.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project with PostCSS and provide a value to `If you want to bundle your CSS files, what will you name the bundle? (press enter to skip`

**What is the expected behavior?**
The bundle name should be used in the generated config.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

```shell
  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  Binaries:
    Node: 8.9.0
    Yarn: Not Found
    npm: 6.0.0
  Browsers:
    Chrome: 66.0.3359.139
    Firefox: Not Found
    Safari: 11.1
  npmGlobalPackages:
    webpack-cli: 2.1.2
```

**Comment by ev1stensberg** [comment] 2018-05-06 15:28
This is skipped if you're not in production

**Comment by DanielRuf** [comment] 2018-05-06 16:06
> This is skipped if you're not in production

Not sure if I understand correctly. We use prod using webpack-cli (webpack-cli init) and the config for the extract text plugin and so on is not correct. No css file is generated.

**Comment by DanielRuf** [comment] 2018-05-07 21:39
> If you have a repo I can debug against that would speed up things

I just ran `webpack-cli init` and nothing more =)

If it is helpful I will do it again and add the generated files to a new repo.

**Comment by ev1stensberg** [comment] 2018-05-07 22:10
That would be nice 💯

**Comment by buoyantair** [comment] 2018-05-21 08:03
I'd love to take this! 🗡 👊 🍰

**Comment by PlayMa256** [comment] 2018-05-21 11:32
@buoyantair go for it. I noticed that when you ask to insert a post-css loader, when we are inserting the plugins array, at the root of modules.exports, it finds by mistake the plugins from postcss-loader.

Somewhere around here: https://github.com/webpack/webpack-cli/blob/master/lib/ast/index.js#L5-L9

**Comment by ev1stensberg** [comment] 2018-05-21 11:46
No, that's wrong. Only the generator will make sure that everything passed to the AST is correct

**Comment by PlayMa256** [comment] 2018-05-21 11:53
Generators are generating correctly, something is happening in between.
```javascript
{ module: { rules: [ [Object], [Object] ] },
  plugins: 
   [ 'new UglifyJSPlugin()',
     'new MiniCssExtractPlugin({ filename:\'asdasd.[chunkhash].css\' })' ],
  entry: '',
  output: 
   { filename: '\'[name].[chunkhash].js\'',
     chunkFilename: '\'[name].[chunkhash].js\'',
     path: 'path.resolve(__dirname, \'dist\')' },
  mode: '\'production\'',
  optimization: 
   { splitChunks: 
      { chunks: '\'async\'',
        minSize: 30000,
        minChunks: 1,
        name: false,
        cacheGroups: [Object] } } }
```
The plugins array is there, the config object is being built correctly.

**Comment by ev1stensberg** [comment] 2018-05-21 11:57
I think the issue is about the css not being used in `entry` or the CSS plugin not being used.

**Comment by buoyantair** [comment] 2018-05-29 09:29
I went through it and I feel like something is going wrong with how the AST is parsed. I mean like the output in the yo-rc.json file seems perfect, so I guess its just how the AST is parsed? I need help with this :/

**Comment by dhruvdutt** [comment] 2018-05-29 09:56
@buoyantair Can you try adding test cases to [recursive-parser](https://github.com/webpack/webpack-cli/blob/next/packages/utils/recursive-parser.test.js) and see the output snapshot?

I would also recommend going through `addProperty()` function [here](https://github.com/webpack/webpack-cli/blob/master/lib/utils/ast-utils.js#L388). This function does the job of generating AST tree for the webpack file.

**Comment by buoyantair** [comment] 2018-05-29 11:17
Just noticed there are no tests for addProperty :3 d

**Comment by dhruvdutt** [comment] 2018-05-29 11:48
@buoyantair Use tests for [recursive-parser](https://github.com/webpack/webpack-cli/blob/next/packages/utils/recursive-parser.test.js) with `init` as last arg inside `defineTest()` function. Add your own fixtures if you want. This is essentially testing `addProperty()`.

**Comment by buoyantair** [comment] 2018-05-29 14:25
All this time I was reading code in master branch!

**Comment by ev1stensberg** [comment] 2018-05-30 14:30
Signature shouldn't change. Change the function invocation if you need to fix the bug.

**Comment by buoyantair** [comment] 2018-05-30 16:25
@ev1stensberg Im on next branch :/

**Comment by buoyantair** [comment] 2018-05-30 16:39
Hmm not sure what you mean by "Signature shouldn't change", because I literally recloned the whole repo and then reinstalled the packages and tried again and I get the same error 🤔 I think I was working just yesterday when I tried to test some changes.

**Comment by dhruvdutt** [comment] 2018-05-30 17:09
@buoyantair I think you can try the changes done in #470. That should fix the error.

**Comment by ev1stensberg** [comment] 2018-06-02 01:39
I think this is fixed in `webpack-cli@3`, please reopen or message me to do that if you think it's still an issue! 😄

**Closed by ev1stensberg** 2018-06-02 01:39 UTC
Labels: Good First Contribution, Init, help wanted

**Comment by DanielRuf** [comment] 2018-06-02 11:01
Ok, will test then =)

**Comment by buoyantair** [comment] 2018-06-03 03:45
@ev1stensberg Is there any specific commit I can look into? :O

**Comment by ev1stensberg** [comment] 2018-06-03 06:05
Check out the `addProperty` function history on master

**Comment by DanielRuf** [comment] 2018-06-04 09:39
So far looks good but it does not seem to work with webpack 4 (generated webpack.prod.js is not used).

**Comment by ev1stensberg** [comment] 2018-06-04 19:54
Could you elaborate on that?

**Comment by DanielRuf** [comment] 2018-06-04 20:42
I guess I will do some more testing with my colleague as this seems to be a bit more complicated (several issues combined).
