### ISSUE TITLE
Cannot find module 'uglify-es'

### ISSUE THREAD

**Issue by hansifer** [webpack/webpack-cli#674] opened 2018-11-03 22:10 UTC
**Describe the bug**

running webpack command after running `npx webpack-cli init` and answering questions results in `Error: Cannot find module 'uglify-es'`

**What is the current behavior?**

running webpack command after running `npx webpack-cli init` and answering questions results in `Error: Cannot find module 'uglify-es'`

**To Reproduce**
1. `npx webpack-cli init`
2. `Will your application have multiple bundles?` answer: n
3. `Which module will be the first to enter the application?` answer: ./src/bg
4. `Which folder will your generated bundles be in?` answer: dist
5. `Will you be using ES2015?` answer: Y
6. `Will you use one of the below CSS solutions?` answer: SASS
7. observe: `Congratulations! Your new webpack configuration file has been created!`
8. `npx webpack`
9. observe error `Cannot find module 'uglify-es'`

**Expected behavior**

no error when running webpack after webpack-cli init

**Screenshots**

N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    uglifyjs-webpack-plugin: ^2.0.1 => 2.0.1
    webpack: ^4.24.0 => 4.24.0
    webpack-cli: ^3.1.2 => 3.1.2

**Additional context**

full error:

Error: Cannot find module 'uglify-es'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\uglify\minify.js:7:17)
    at Module._compile (node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\uglify\Runner.js:29:15)
    at Module._compile (node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\index.js:40:15)
    at Module._compile (node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\cjs.js:3:18)
    at Module._compile (node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (node_modules\v8-compile-cache\v8-compile-cache.js:159:20)

**Comment by dhruvdutt** [comment] 2018-11-04 09:06
Couldn't reproduce this. Can you try outputting `npm list uglify-es`? I think your installation failed due to some reason and hence it could not find the module.

<img width="565" alt="screenshot 2018-11-04 at 1 34 03 pm" src="https://user-images.githubusercontent.com/5961873/47961724-87713800-e036-11e8-93f6-ee011b70f2be.png">

**Comment by evenstensberg** [comment] 2018-11-04 13:07
Npx doesn't install a lock-file I think, maybe try to do it without npx?

**Comment by hansifer** [comment] 2018-11-04 15:46
I tried running webpack via npm script as well. same result.

I discovered that when i rename the generated webpack.dev.js to
webpack.config.js, it gets past this particular error.

**Comment by hansifer** [comment] 2018-11-04 20:13
> Does it also happen on `npx webpack-cli --config webpack.dev.js`?

I assume you mean `npx webpack --config webpack.dev.js` since the above command produces an error `Cannot find module 'webpack.dev.js'` ?

With the latest version of webpack-cli it is producing a `webpack.prod.js` file now and I am no longer able to repro this bug (with either a `webpack.prod.js` or a renamed `webpack.dev.js` file).

BTW, I did confirm previously that `npm list uglify-es` output the following:
```
`-- webpack@4.24.0
  `-- uglifyjs-webpack-plugin@1.3.0
    `-- uglify-es@3.3.9
```

**Comment by evenstensberg** [comment] 2018-11-10 16:14
Could you try to do `--config=webpack.dev.js`?

**Comment by EugeneHlushko** [comment] 2018-11-12 10:12
@hansifer The reason behind this: "I discovered that when I rename the generated webpack.dev.js to
webpack.config.js, it gets past this particular error, but the reason for this is not obvious."

is that `webpack-cli` looks for `./webpack.config.js` file when no config file was passed.

**Comment by evenstensberg** [comment] 2019-02-05 14:10
Closing as this looks like it is fixed, please comment or post a SO issue and I'll be happy to help

**Closed by evenstensberg** 2019-02-05 14:10 UTC
Labels: needs investigation, question: general
