### ISSUE TITLE
Add Attic Files generated when building using yarn to .gitignore

### ISSUE THREAD

**Issue by Deathrow77** [webpack/webpack-cli#1199] opened 2020-02-01 05:36 UTC
**Describe the bug**

When building using yarn, a new folder named "attic" is generated which contains a few unnecessary server files.

**What is the current behavior?**
The attic folder is not added to .gitignore which pushes these files with every commit.

**To Reproduce**
1. Go to 'terminal'
2. Execute 'yarn'
3. Go to your webpack-cli repository folder and find a folder named 'attic'
4. Build the cli and try committing. You'll notice that attic folder is also being committed although it is not relevant to the cli itself.

**Expected behavior**
attic folder should not be included in the commit to git.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by rishabh3112** [comment] 2020-02-01 08:37
Thanks for reporting!
I can't reproduce issue on my side, I use yarn and haven't experienced any such issues.
Try re cloning project in a separate empty folder and follow steps in our Contribution Guide.

**Comment by ematipico** [comment] 2020-02-01 09:37
Also, we use npm for our project, not yarn. So we suggest to stick with npm to avoid these issues.

**Comment by anshumanv** [comment] 2020-02-07 17:33
Not able to reproduce, did you try recloning the project @Deathrow77 ?

Otherwise, this can be closed.

**Comment by ematipico** [comment] 2020-02-08 11:17
Closing issue as it's not reproducable

**Closed by ematipico** 2020-02-08 11:17 UTC
Labels: question
