### ISSUE TITLE
Cannot install webpack-cli

### ISSUE THREAD

**Issue by clairepham91** [webpack/webpack-cli#313] opened 2018-03-06 10:05 UTC
I am getting
`An unexpected error occurred: "https://github.com/ev1stensberg/generator.git: getaddrinfo ENOTFOUND github.com github.com:443"`
when running ` yarn add webpack-cli -D`

**Comment by montogeek** [comment] 2018-03-06 10:36
Please try again, it was an temporary network error

**Comment by dhruvdutt** [comment] 2018-03-06 10:38
@clairepham91 Are you behind a proxy?

**Comment by andrewpmontgomery** [comment] 2018-03-06 10:54
Similar error with `npm install webpack-cli`

```Error while executing:
C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ev1stensberg/generator.git

ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.
```

Most corporate networks don't allow ssh, so this will never work. I'll revert to webpack-cli 2.0.9 until this is fixed.

**Comment by clairepham91** [comment] 2018-03-06 11:09
@dhruvdutt yes I am

**Comment by dhruvdutt** [comment] 2018-03-06 11:10
@clairepham91 This is duplicate of #161. Can you please close this and discuss over there?

**Comment by ematipico** [comment] 2018-03-06 11:11
Duplicate of #161

**Closed by ematipico** 2018-03-06 11:11 UTC
