### ISSUE TITLE
Base layout design for webpackGUI

### ISSUE THREAD

**Issue by theaayush8999** [webpack/webpack-cli#769] opened 2019-03-03 16:12 UTC
@rishabh3112 @evenstensberg 
**As we are going for preact in the frontend.
I'm creating the base component of GUI and @rishabh3112 is that `init` endpoint complete or I can contribute there too.**

**GUI concept tell me if you like it !!!**

![main-template-webpack svg](https://user-images.githubusercontent.com/32022442/53697957-9d341580-3dfc-11e9-8fa2-203a0fa8fecc.png)

**Comment by rishabh3112** [comment] 2019-03-03 16:22
Hi @theaayush8999, thanks for sharing your ideas for layout of webpack ui. I would recommend you to share your design over #654 for visibility. Currently we are in contact with designers and you can track progress on it there.

**Comment by rishabh3112** [comment] 2019-03-03 17:42
@theaayush8999 close this issue for now, further discussions would be on issue 654. This is duplicate of that issue.

**Closed** 2019-03-03 17:45 UTC
