### ISSUE TITLE
[ENHANCEMENT]: Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#868] opened 2019-04-28 20:49 UTC
```
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Improve error handling by adding the `catch` block.

https://github.com/webpack/webpack-cli/blob/06b4929c130e30763b9b70d79ab6ae182f6d4fa9/packages/generators/init-generator.ts#L85

https://github.com/webpack/webpack-cli/blob/06b4929c130e30763b9b70d79ab6ae182f6d4fa9/packages/generators/remove-generator.ts#L64

https://github.com/webpack/webpack-cli/blob/06b4929c130e30763b9b70d79ab6ae182f6d4fa9/packages/generators/utils/entry.ts#L35

**And many more**

**Comment by jamesgeorge007** [comment] 2019-05-28 07:40
@pranshuchittora I would like to take this up :+1:

**Comment by evenstensberg** [comment] 2019-05-28 08:37
@pranshuchittora could you use the template that will help people triage the issue?

**Comment by pranshuchittora** [comment] 2019-05-30 18:35
`template`?
Pls elaborate.

**Comment by misterdev** [comment] 2019-05-30 19:47
The following is the issue template Even is talking about :)


---



**Describe the bug**

A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

**What is the current behavior?**

This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by pranavsrivatsaVL** [comment] 2019-08-12 08:53
Hello  @pranshuchittora  @evenstensberg , 
Could I look into this issue if it is not assigned to anyone ?

**Comment by evenstensberg** [comment] 2019-08-13 16:38
Yes!

**Comment by pranavsrivatsaVL** [comment] 2019-08-15 01:48
I will start work on this . Thank you @evenstensberg .

**Comment by pranavsrivatsaVL** [comment] 2019-08-15 02:53
Thank you @evenstensberg 
Started working on this.

**Comment by manosriram** [comment] 2020-01-29 15:45
Is this issue still around? If so, can I work on it ?

**Comment by ematipico** [comment] 2020-01-30 07:10
@manosriram go ahead!

**Comment by evilebottnawi** [comment] 2020-07-31 10:57
bump

**Comment by pranvatsa** [comment] 2020-08-03 10:44
This still seems to be open. Last time i commented i could not understand the issue and lacked understanding about promises. 
I could give this another go now. Will start working on this

**Comment by pranshuchittora** [comment] 2020-08-03 15:48
Hi @pranvatsa 
_The issue was raised more than a year ago, so things might have changed a lot._

Speaking of the root problem encountered earlier, was that the rejected promises were not handled for any errs/exceptions.

There are some file references in the description (**outdated**), in which the promise resolution was not handled properly. 

As far as I remember the unhandled promise rejection will cause the process to exit in the newer versions of `node`.

One of the solutions is to catch every promise rejections or attaching a listener to the `unhandledRejection` event.

https://nodejs.org/api/process.html#process_event_unhandledrejection

I am not sure about the currently implemented error handling architecture :)

**Comment by pranvatsa** [comment] 2020-08-03 15:52
Understood :) 
I wanted to verify if this has already been handled by changes made by others and close this issue. 
So wanted to know how you got this warning earlier or steps to run the code locally

**Comment by pranshuchittora** [comment] 2020-08-03 16:25
Pardon, but I don't remember the exact steps to reproduce the following issue as far as I remember,  I was debugging one flow and my changes caused one of the promise to fail which in turn threw the following warning.

Just a thought :)
You can probe into any promise which you think is not handled properly, and then try to explicitly reject the promise, if that's not been handled then you may see an `UnhandledPromiseRejectionWarning`.

**Sample**
```js
function failingPromise() {
  return new Promise(function (resolve, reject) {
    reject();
  });
}
let initPromise = failingPromise();
initPromise.then(function () {
  console.log("Promise Resolved");
});

**Output**
```
(node:10592) UnhandledPromiseRejectionWarning: undefined
(node:10592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by evilebottnawi** [comment] 2020-10-03 14:37
I think it is fixed in latest rc, let's close, anyway if somebody faced with the issue, feel free to open a new issue

**Closed by evilebottnawi** 2020-10-03 14:37 UTC
Labels: Good First Contribution, enhancement
