### ISSUE TITLE
Interesting behavior when using `info` as a value for `--info-verbosity`

### ISSUE THREAD

**Issue by lukaselmer** [webpack/webpack-cli#1383] opened 2020-03-26 21:18 UTC
The command `npx webpack-cli --watch --progress --info-verbosity info` executes `npx webpack-cli info` instead of setting the flag `--info-verbosity` to `info`.

Examples to reproduce the issue:

```
> npx webpack-cli --version --info-verbosity none
npx: installed 204 in 17.126s
3.3.11
=> all good

> npx webpack-cli --version --info-verbosity verbose
npx: installed 204 in 16.779s
3.3.11
=> all good

>npx webpack-cli --version --info-verbosity thisisatest
npx: installed 204 in 21.704s
3.3.11
=> all good

> npx webpack-cli --version --info-verbosity info
npx: installed 204 in 12.299s
The command moved into a separate package: @webpack-cli/info
Would you like to install info? (That will run yarn add -D @webpack-cli/info) (yes/NO) : %
=> tries to install the info package, so it can run `webpack-cli info`!
```

**What is the current behavior?**

```
> npx webpack-cli --version --info-verbosity info
npx: installed 204 in 12.299s
The command moved into a separate package: @webpack-cli/info
Would you like to install info? (That will run yarn add -D @webpack-cli/info) (yes/NO) : %
=> tries to install the info package (or displays the info if already installed)
=> so it actually runs `webpack-cli info` :(
```

**To Reproduce**

See above

**Expected behavior**

```
> npx webpack-cli --version --info-verbosity info
npx: installed 204 in 12.299s
3.3.11
```

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
> npx webpack-cli --watch --info-verbosity info

undefined

watch is an invalid option

info-verbosity is an invalid option

infoVerbosity is an invalid option

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 512.84 MB / 16.00 GB
  Binaries:
    Node: 12.16.1 - ~/.asdf/installs/nodejs/12.16.1/bin/node
    Yarn: 1.22.4 - ~/.asdf/installs/nodejs/12.16.1/bin/yarn
    npm: 6.14.4 - ~/w/cockpit/node_modules/.bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    tsconfig-paths-webpack-plugin: ^3.2.0 => 3.2.0
    webpack: ^4.42.1 => 4.42.1
    webpack-bundle-analyzer: ^3.6.1 => 3.6.1
    webpack-cli: ^3.3.11 => 3.3.11
```

**Comment by snitin315** [comment] 2020-03-29 08:56
@lukaselmer could you say the same against beta?

![Screenshot from 2020-03-29 14-24-50](https://user-images.githubusercontent.com/46647141/77845026-1e5d0800-71c9-11ea-8140-0e8bb42fac6a.png)

**Comment by lukaselmer** [comment] 2020-03-30 12:12
> @lukaselmer could you say the same against beta?
> 
> ![Screenshot from 2020-03-29 14-24-50](https://user-images.githubusercontent.com/46647141/77845026-1e5d0800-71c9-11ea-8140-0e8bb42fac6a.png)

@snitin315: Yes, the issue still persists in the beta release:

```
> npx webpack-cli@4.0.0-beta.8 --version --info-verbosity verbose
npx: installed 91 in 3.508s
4.0.0-beta.8
[...error unrelated to the issue, see screenshot]

> npx webpack-cli@4.0.0-beta.8 --version --info-verbosity info
npx: installed 91 in 3.876s
The command moved into a separate package: @webpack-cli/info
Would you like to install info? (That will run yarn add -D @webpack-cli/info) (yes/NO) : 
[...error unrelated to the issue, see screenshot]

> npx webpack-cli --version --info-verbosity verbose
3.3.11

> npx webpack-cli --version --info-verbosity info
The command moved into a separate package: @webpack-cli/info
Would you like to install info? (That will run yarn add -D @webpack-cli/info) (yes/NO) : %                                                                                                                         
```

![image](https://user-images.githubusercontent.com/326935/77910361-4f077500-728f-11ea-8b6f-e0b47732cad5.png)

@snitin315 what happens when you run `npx webpack-cli --version --info-verbosity info` and `npx webpack-cli@4.0.0-beta.8 --version --info-verbosity info` on your machine?

**Comment by evilebottnawi** [comment] 2020-03-31 11:26
Thanks

**Comment by snitin315** [comment] 2020-04-02 04:31
Working for me in beta.
![Screenshot from 2020-04-02 10-00-37](https://user-images.githubusercontent.com/46647141/78210808-e9063200-74c8-11ea-842e-4cbb02026c4f.png)

**Comment by snitin315** [comment] 2020-04-02 04:36
> @snitin315 what happens when you run npx webpack-cli --version --info-verbosity info and npx webpack-cli@4.0.0-beta.8 --version --info-verbosity info on your machine?

`npx webpack-cli --version --info-verbosity info` works fine
`npx webpack-cli@4.0.0-beta.8 --version --info-verbosity info ` this installs beta first and works fine.

![Screenshot from 2020-04-02 10-05-48](https://user-images.githubusercontent.com/46647141/78211060-9da05380-74c9-11ea-865b-95e577d70895.png)

**Comment by evilebottnawi** [comment] 2020-04-02 10:56
@snitin315 Can you send tests to ensure we don't have that problem?

**Comment by snitin315** [comment] 2020-04-02 11:05
Sure , on it.

**Comment by anshumanv** [comment] 2020-04-03 04:41
@evilebottnawi, was able to reproduce this on a machine which doesn't have webpack installed, right now we're expecting the user to supply the webpack version of their choice via peerDependencies, and since when run via npx and the user doesn't have webpack installed globally this throws, only solution that I can think of right now is moving it to dependencies, please let me know if there are any alternatives, will fix appropriately.

![image](https://user-images.githubusercontent.com/21009455/78324800-5c747600-7593-11ea-853b-c66e2544f83c.png)

**Comment by evilebottnawi** [comment] 2020-04-03 10:55
@anshumanv we can't fix it, people should have webpack in deps, anyway I think we can improve DX, for example check that webpack is not installed and answer question about installation, for example:
```
Looks webpack is not installed, do you want install? [Y,n]
```

**Closed** 2020-09-25 14:13 UTC
Labels: Bug
