### ISSUE TITLE
webpack serve does not respect configuration for supplied mode

### ISSUE THREAD

**Issue by tcrossland** [webpack/webpack-cli#1976] opened 2020-10-22 18:01 UTC
According to the documentation [here](https://webpack.js.org/api/cli/#default-configurations), when `--mode development`is specified, the config file `webpack.config.dev.js` should take precedence over `webpack.config.prod.js`. However, configuration is actually loaded from both files, with production configuration overriding development configuration.

**What is the current behavior?**

configuration from `webpack.config.prod.js overrides` configuration from `webpack.config.dev.js`, regardless of whether `--mode development` or `--mode production` is specified.

**To Reproduce**

1. Create two config files (`webpack.config.dev.js`, `webpack.config.prod.js`)
2. Run `webpack --mode development serve`
3. Observe that production configuration takes effect

**Expected behavior**

Configuration should be loaded only from `webpack.config.dev.js` when mode development is specified

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.90 GB / 32.00 GB
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 86.1.15.72
    Chrome: 86.0.4240.111
    Firefox: 81.0
    Safari: 14.0
  Packages:
    html-webpack-plugin: ^4.5.0 => 4.5.0 
    image-webpack-loader: ^7.0.1 => 7.0.1 
    optimize-css-assets-webpack-plugin: ^5.0.4 => 5.0.4 
    terser-webpack-plugin: ^5.0.0 => 5.0.0 
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    webpack: ^5.2.0 => 5.2.0 
    webpack-cli: ^4.1.0 => 4.1.0 
    webpack-dev-server: ^3.10.3 => 3.11.0 
    webpack-merge: ^5.2.0 => 5.2.0 
    webpack-pwa-manifest: ^4.2.0 => 4.2.0 
```

**Comment by evilebottnawi** [comment] 2020-10-22 18:03
How `serve` related to the problem?

**Comment by evilebottnawi** [comment] 2020-10-22 18:04
And I can't reproduce, please provide more steps

**Comment by tcrossland** [comment] 2020-10-22 20:02
Sorry for the delay, I've put together a fairly simple example:

https://github.com/tcrossland/webpack-serve-issue

Maybe the issue is actually with webpack-dev-server?

**Comment by evilebottnawi** [comment] 2020-10-22 20:05
I will look at this in near future

**Comment by tcrossland** [comment] 2020-10-23 07:23
This might be a documentation issue. The following works:

`webpack serve --config webpack.config.dev.js`

But this does not:

`webpack --mode development serve`

**Comment by snitin315** [comment] 2020-10-23 09:09
Does this work `webpack serve --mode development` ?

**Comment by tcrossland** [comment] 2020-10-25 07:12
> Does this work `webpack serve --mode development` ?

No, the mode is ignored too.

**Comment by alexander-akait** [comment] 2020-12-25 15:27
Fixed in master, we remove this behavior, because it was broken and never work as expected (we have to remove this before, but forgot about it, we are very sorry), you need provide `--config` right now

**Closed by alexander-akait** 2020-12-25 15:27 UTC
Labels: Bug
