### ISSUE TITLE
Install fails behind corporate proxy (SSH block?)

### ISSUE THREAD

**Issue by brownieboy** [webpack/webpack-cli#132] opened 2017-05-09 22:31 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
Global install `npm install -g webpack-cli` fails behind a corporate proxy.  Error is:

> Error: Command failed: git -c core.longpaths=true config --get remote.origin.url

I suspect that this is because our corporate proxy blocks SSH access to the internet (as many of them do).

**What is the expected behavior?**
Install should not crash like this simply because SSH is unavailable.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
We need an option to have the installer to execute its `git clone` tasks via HTTPS instead of SSH.  At the very least, the installer should trap this error and tell the user what the problem is.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Windows 7, but it also happened on a Linux Mint VM behind the same corporate proxy.

**Comment by ev1stensberg** [comment] 2017-05-09 22:43
If you're cloning this instead of downloading directly, you can use `https`. Other than that, you can also download the source and run `npm link` within your shell to get the same behaviour as `npm install -g webpack-cli`. Did this help? :) Happy to elaborate!

**Comment by brownieboy** [comment] 2017-05-09 22:57
Thanks for that very quick response, @ev1stensberg .

I've not used `npm link` before, but when I tried it I got the same error.  My exact command steps were:
`npm remove webpack-cli -g
git clone https://github.com/webpack/webpack-cli.git
cd webpack-cli
npm link`

That seemed to kick the install process off again, eventually resulting in the same error.

Actually, the repository that seems to be triggering the error is `git://github.com/kalcifer/recast.git`.  So maybe I need to clone that one (too)?

**Comment by ev1stensberg** [comment] 2017-05-09 23:06
It may be. You can change the `package.json` in the forked version to `https`, and it should in theory work for your case. Note that `recast` isn't the only forked repo, but also `Yeoman-Generator`. 

https://coderwall.com/p/q_gh-w/fork-and-patch-npm-moduels-hosted-on-github

Also, I think you should use `npm uninstall webpack-cli -g` instead, remove isn't a valid command, is it? 

`npm link` is a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) that will allow you to execute the clone from any directory. Happy to help!

**Comment by ev1stensberg** [comment] 2017-05-09 23:09
Also a note to add is that we're removing these forks soon. For your SSH problems -> 
http://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by brownieboy** [comment] 2017-05-09 23:18
Thanks again, @ev1stensberg.

I think I'll wait until you've removed the forks from the installer.

FYI, `remove` is a valid alias to `uninstall`, see https://docs.npmjs.com/cli/uninstall.  I should probably use the proper command though!

**Comment by ev1stensberg** [comment] 2017-05-09 23:20
Oooh, nitty! No need to wait, I think this is doable. Either do as in below picture and do `npm link`, or you could try out the SO link I've commented. 

![skjermbilde 2017-05-10 kl 01 19 41](https://cloud.githubusercontent.com/assets/16735925/25876628/c2d016b0-351e-11e7-95fe-1e2b39f4719e.png)

**Comment by brownieboy** [comment] 2017-05-10 02:10
Thanks again.  That got be a bit further, but I've hit further problems.

I was able to install webpack-cli using the `npm link` method.  But trying to execute like so:
```
webpack-cli init webpack-addons-testcli
```
Throws the error 

> TypeError: Package isn't registered on npm.

No indication as to which package this is.

Also, the installation of webpack-cli caused all of my other global packages to throw the error:

> npm ERR! extraneous:

when I try to list them with an `npm list -g --depth=0`.  This error went away when I uninstalled webpack-cli.

Thanks for your help, so far, but this is all getting a bit messy.  I'd rather wait until you've removed the forks from the installer as you said.

**Comment by dkfiresky** [comment] 2017-05-10 10:12
Possibly setting this option could help:

```
> git config --global url."https://".insteadOf git://
```

~/.gitconfig
```
[url "https://"]
insteadOf = git://
```

**Comment by TheLarkInn** [comment] 2017-05-13 05:20
@brownieboy Let me know if @dkfiresky 's suggestion was helpful or if we need to assist any further.

**Comment by anyulled** [comment] 2017-05-23 08:34
@dkfiresky I'm having the same error nad tried your suggestion and still didn't work.

**Comment by ev1stensberg** [comment] 2017-05-23 08:36
Can you send me your `.gitconfig` per mail @anyulled ? See patterns of this issue on windows, need some context around npm. Should work at our end.

**Comment by anyulled** [comment] 2017-05-23 08:47
@ev1stensberg my .gitconfig only has this now:

[user]
	name = alrs
	email = myusername@somedomain.com
[url "https://"]
	insteadOf = git://

**Comment by ev1stensberg** [comment] 2017-05-23 08:55
Can I get yours as well @brownieboy ?

**Comment by ev1stensberg** [comment] 2017-06-30 17:20
Any update on this?

**Comment by ev1stensberg** [comment] 2017-12-17 17:23
This is probably a dupe of #182, so let's resume discussion over there!

**Closed by ev1stensberg** 2017-12-17 17:23 UTC
Labels: CLI, question
