### ISSUE TITLE
CLI: --silent flag behavior

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1557] opened 2020-05-19 02:37 UTC
**Describe the bug**

webpack-cli supports `--silent` flag whose functionality is stated as `Disable any output that webpack makes`.

**What is the current behavior?**
This flag doesn't seem to do anything at all.

**To Reproduce**

`webpack-cli --silent`

**Expected behavior**

as per docs, it should disable any output that webpack makes.

**Screenshots**
![Screenshot at 2020-05-19 07-54-46](https://user-images.githubusercontent.com/46647141/82277947-b47e0500-99a6-11ea-8228-7bd47a729e3d.png)

**Additional context**

- I think we should consider it's existence, As per roadmap we should support only popular flags.

- Also `webpack --stats none` does a better job in disabling webpack output. Maybe it's a shortcut for `--stats=none` but it's not implemented like this. 

/cc @evilebottnawi @rishabh3112

**Comment by anshumanv** [comment] 2020-05-19 05:42
Duplicate of https://github.com/webpack/webpack-cli/issues/1324

**Closed by anshumanv** 2020-05-19 05:42 UTC
