### ISSUE TITLE
promise may be resolved prematurely

### ISSUE THREAD

**Issue by GeassCoder** [webpack/webpack-cli#767] opened 2019-02-28 18:49 UTC
**Describe the bug**
https://github.com/webpack/webpack-cli/blob/master/bin/prompt-command.js#L11

Just curious if this is the real intention. If I understand it correctly this will always resolve the promise immediately, and the resolve() and reject() in the "error" and "exit" handlers below will have no effect.

**Comment by rishabh3112** [comment] 2019-03-01 12:40
Thanks for reporting @GeassCoder, there is an error reported at #741 due to this.
I am resolving it at #742 .

**Comment by evenstensberg** [comment] 2019-03-03 22:12
This is a bug, being fixed soon

**Comment by rishabh3112** [comment] 2019-03-04 17:40
This is duplicate of #741.

**Comment by rishabh3112** [comment] 2019-03-22 08:42
@GeassCoder Fix shipped at webpack-cli v3.3.0. Update to get the fix :+1:

**Closed** 2019-04-08 18:43 UTC
Labels: Bug
