### ISSUE TITLE
Cannot install webpack-cli

### ISSUE THREAD

**Issue by bponomarenko** [webpack/webpack-cli#314] opened 2018-03-06 10:54 UTC
I have special setup where I don't have git installed in the same environment, where I have npm. In this setup `webpack-cli` installation fails with the following error:
```
$ npm i webpack-cli -D
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

Why git is needed for cli installation?

**Comment by dhruvdutt** [comment] 2018-03-06 11:01
I think it's because of a fork we're using.

@bponomarenko Can you please close this issue and discuss at #161?

**Comment by ematipico** [comment] 2018-03-06 11:08
Closing, duplicate of #161

**Closed by ematipico** 2018-03-06 11:08 UTC

**Comment by bponomarenko** [comment] 2018-03-06 11:23
@dhruvdutt @ematipico Thanks!
