### ISSUE TITLE
[webpack-cli 4.0.0] Unknown argument: --env.source=src/examples/*

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack-cli#1942] opened 2020-10-13 23:54 UTC
# Bug report

After migrating to webpack cli 4.0.0 i get the following error:
```
~/MyDev/ljs_app/trunk/periscope $ npx webpack --progress --env.source="src/examples/*"
[webpack-cli] Unknown argument: --env.source=src/examples/*
? Which flags do you want to use? …
✔ --entry: The entry point(s) of your application e.g. ./src/main.js
✔ --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
✖ Which flags do you want to use? · No items were selected
[webpack-cli] Action Interrupted, use webpack-cli help to see possible options.
```

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

`npx webpack --progress --env.source="src/examples/*"`

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 14.13.0
Operating System: macOS 10.15.7
Additional tools:

**Comment by anshumanv** [comment] 2020-10-14 09:03
This format is no longer supported in v4, we're working to enhance it here - https://github.com/webpack/webpack-cli/pull/1939 

Duplicate of https://github.com/webpack/webpack-cli/issues/1932

**Closed** 2020-10-14 10:46 UTC

**Comment by nevcos** [comment] 2021-05-26 11:05
@anshumanv This breaking change is not referred on https://webpack.js.org/migrate/5/ or CHANGELOG, it's worth adding it.

This change is highly inconvenient because it affects CI scripts, which in our case need to work both with webpack 4 and 5.
Is there any syntax that works on both webpack-cli v3 and v4?

Thanks!

**Comment by alexander-akait** [comment] 2021-05-26 11:11
@nevcos `--env platform=staging --env production --env foo.bar=baz`

**Comment by nevcos** [comment] 2021-05-26 11:27
@alexander-akait It doesn't work the same way:
```
# webpack-cli 3:
webpack --env.myFlag=true # options is an object: {"myFlag":"true"}

webpack --env myFlag=true # options is a string: "myFlag=true"

# webpack-cli 4:
webpack --env myFlag=true # options is an object: {"WEBPACK_BUNDLE":true,"WEBPACK_BUILD":true,"myFlag":"true"}

**Comment by alexander-akait** [comment] 2021-05-26 11:42
If you need boolean value, you need just use `--env myFlag` (without any values)

**Comment by nevcos** [comment] 2021-05-26 11:50
@alexander-akait It was just an example, in my case I need to send a string URL for source maps location.
I'll fix the CI script with an ugly `if [[ ${WEBPACK_VERSION} == 4* ]]`, hopefully I'll be able to remove it soon 😅.
