### ISSUE TITLE
webpack-cli migrate webpack.config.js ERROR

### ISSUE THREAD

**Issue by private-ryan23** [webpack/webpack-cli#541] opened 2018-07-09 11:17 UTC
I'm updating a **webpack.config.js** using and this command `webpack-cli migrate weebpack.config.js`

I'm starting a new project with webpack mini test sample so 
I create a directory and run `npm init` then run `npm i webpack --save-dev`
I install webpack-cli `npm i webpack-cli` then i run `webpack init`  automatically install a new **webpack.dev.js**
I run `webpack-cli migrate webpack.config.js` this pop the error

```
C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\@webpack-cli\migrate\index.js:11
const { validate } = process.webpackModule;`
        ^

TypeError: Cannot destructure property `validate` of 'undefined' or 'null'.
    at Object.<anonymous> (C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\@webpack-cli\migrate\index.js:11:30)
    at Module._compile (C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at promptForInstallation (C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\webpack-cli\bin\prompt-command.js:108:3)
    at C:\Users\Spiralytics04\Desktop\webpack-sample-cli\node_modules\webpack-cli\bin\cli.js:45:37
```

**Comment by ematipico** [comment] 2018-07-09 14:16
Hi! Thanks for filling the issue, please next time don't delete the template! Couple of questions:

1. You didn't mention the file webpack.config.js in your problem, where does it come from?
2. Why do you use migrate? Looks like you're creating a new project

**Comment by IzaGz** [comment] 2018-07-09 20:03
same problem

**Comment by IzaGz** [comment] 2018-07-09 20:10
i have tried to switch to version 2- but go the
`TypeError: Cannot read property 'length' of null`
https://github.com/webpack/webpack-cli/issues/542

**Comment by ev1stensberg** [comment] 2018-07-10 03:46
Which version are you lads at? We need more information 👍

**Comment by IzaGz** [comment] 2018-07-11 09:33
this issue error happens on webpack-cli 308

**Comment by ev1stensberg** [comment] 2018-07-11 15:21
Upgrade to version `3.1.2` and up, an update to the latest version would be the best for you! :)

**Comment by ev1stensberg** [comment] 2018-07-18 02:12
Yep. I'll submit a fix shortly

**Comment by ev1stensberg** [comment] 2018-07-18 02:46
Fixed on master now. Will publish a new release once @dhruvdutt has fixed the breaking tests in bintestcases.

**Closed by ev1stensberg** 2018-07-18 02:46 UTC
Labels: needs investigation, question: general

**Comment by xtx1130** [comment] 2018-07-18 08:05
The same issue and I use:
```json
"webpack-cli": "git+https://github.com/webpack/webpack-cli.git#master"
```

**Comment by DelfsEngineering** [comment] 2018-10-29 02:40
Any update on this?

**Comment by ematipico** [comment] 2018-10-29 11:49
It's supposed to be resolved. If you still have this issue, please file a new issue with information of how to reproduce it
