### ISSUE TITLE
Doesn't seem to work with Yarn PnP

### ISSUE THREAD

**Issue by jlkiri** [webpack/webpack-cli#1434] opened 2020-04-09 09:57 UTC
**Describe the bug**

I am trying to use `webpack@5.0.0-beta.14` with `webpack-cli@4.0.0-beta.8`. I am using Yarn 2 with workspaces. When I run my build command `webpack --config webpack.config.js` it tells me that I need to install `webpack-cli` but I already installed it. Is PnP not supported?

**What is the current behavior?**

**To Reproduce**

1. [Create](https://yarnpkg.com/getting-started) a Yarn 2 project with [workspaces](https://yarnpkg.com/features/workspaces).

2. Install webpack and webpack-cli to one of the workspaces.
3. Write a random file.
4. Run `webpack`

**Expected behavior**

A bundle is generated.

**Actual behavior**

Error:

```
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): no
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.
```

**Additional context** 

Didn't work with `webpack-cli` v3 either.

**Comment by evilebottnawi** [comment] 2020-04-09 11:15
That error from webpack, I can't reproducible

**Comment by aman29271** [comment] 2020-04-09 18:43
I can't reproduce the error. May be its the problem with Yarn PnP. Can you please show the output of `node node_modules/.bin/webpack-cli info` ?

**Comment by jlkiri** [comment] 2020-04-10 02:44
For some reason I can't reproduce it with the exact same error anymore so I'm going to close the issue.

**Comment by jlkiri** [comment] 2020-04-10 03:13
Ok, I could reproduce it again so reopening the issue.
Make sure that you install `webpack` and `webpack-cli` with

```
yarn workspace <your_workspace> add webpack webpack-cli
```

Here's the `package.json` of my workspace:

{
  "name": "test",
  "scripts": {
    "build": "webpack",
  },
  "devDependencies": {
    "typescript": "^3.8.3",
    "webpack": "5.0.0-beta.14",
    "webpack-cli": "4.0.0-beta.8"
  },
}

@aman29271 I can't because when you use PnP there is no `node_modules` folder.

**Comment by aman29271** [comment] 2020-04-10 06:43
I have never used Yarn Pnp. But it looks like it uses some `.pnp.js` file to keep track of packages and dependencies. It  needs  `installConfig:{"pnp":true}` in package.json file, for more details about Yarn PnP see [here](https://classic.yarnpkg.com/en/docs/pnp/getting-started). Instead of running `node node_modules/.bin/webpack` you need to run simply `yarn webpack `  or `yarn <package-name>`because there is not any `node_modules` folder in Yarn PnP. So, for me it turns out to be working. Let me know if it works for you.

**Comment by keithlayne** [comment] 2020-05-03 19:24
Just ran into this, and discovered that the above behavior happens when using yarn 2 in `strict` mode.  In `loose` mode, it works for me.

**Comment by keithlayne** [comment] 2020-05-03 19:38
For yarn 2 in strict mode, add this to your `.yarnrc.yml`:

```yml
packageExtensions:
  webpack@*:
    peerDependencies:
      webpack-cli: '*'
    peerDependenciesMeta:
      webpack-cli:
        optional: true
```

**Comment by aman29271** [comment] 2020-05-04 04:00
Thanks for sharing

**Comment by nicolo-ribaudo** [comment] 2020-07-10 20:38
@arcanis Do you think that this is something that could be added to `plugin-compat`?

**Comment by arcanis** [comment] 2020-07-10 20:57
@nicolo-ribaudo the actual fix is simply to call `yarn webpack-cli` instead of `yarn webpack`. I think it's a decent workaround, does that sound acceptable?

**Comment by nicolo-ribaudo** [comment] 2020-07-10 21:02
It is enough, I didn't notice that fix :upside_down_face:

**Comment by merceyz** [comment] 2020-07-20 23:36
Fix for webpack 5 is here: https://github.com/webpack/webpack/pull/11189
Fix for webpack 4 is here: https://github.com/webpack/webpack/pull/11190

**Comment by evilebottnawi** [comment] 2020-08-01 13:52
Fixed on webpack side, if you faced with PnP problem again, feel free to open a new issue

**Closed by evilebottnawi** 2020-08-01 13:52 UTC
