### ISSUE TITLE
Deprecated warning for webpack-cli

### ISSUE THREAD

**Issue by heyalbert** [webpack/webpack-cli#429] opened 2018-05-03 10:26 UTC
```
•100% ➜ npm install webpack-cli -D
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

+ webpack-cli@2.1.2
updated 1 package in 15.609s
```

using npm 6.0.0 and node 10.0.0

**Comment by ematipico** [comment] 2018-05-04 07:28
Yes, it's a duplicate.

**Comment by ematipico** [comment] 2018-05-04 07:29
Duplicate of #287

**Closed by ematipico** 2018-05-04 07:29 UTC
