### ISSUE TITLE
Can't resolve 'fs/promises'

### ISSUE THREAD

**Issue by eng-dibo** [webpack/webpack-cli#1612] opened 2020-06-04 10:50 UTC
I use the latest version of nodejs, typescript and webpack.

for this code:
```
import * from "fs/promises"
```
running `tsc` compiles the files without any problem, but with `webpack` I got the error 
`Module not found: Error: Can't resolve 'fs/promises'`

**Comment by evilebottnawi** [comment] 2020-06-04 11:10
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please read documentation https://webpack.js.org/configuration/node/

**Closed by evilebottnawi** 2020-06-04 11:10 UTC

**Comment by angelhdz** [comment] 2021-04-09 00:34
Uuugh I'm having this issue too. I started learning Electron with TypeScript and Vue 3, and everthing works, except for this issue trying to uses the fs module with the promises module to have the async readFile... I've been reading a looot of pages about webpack, trying different things, and nothing solves it!!!

**Comment by alexander-akait** [comment] 2021-04-09 10:23
You feedback is not help, please provide example how we can reproduce it

**Comment by angelhdz** [comment] 2021-04-12 01:47
> You feedback is not help, please provide example how we can reproduce it

Are you a bot, or an arrogant person? My feedback is important because I'm a user of this technology, and it did not work. 

Or do you want me to open a new Issue and then hit me with the **"this is a duplicate of..."???**

_If you don't have anything good to say, better don't say anything because what you just said is not help either._

**Comment by angelhdz** [comment] 2021-04-12 01:54
> I use the latest version of nodejs, typescript and webpack.
> 
> for this code:
> 
> ```
> import * from "fs/promises"
> ```
> 
> running `tsc` compiles the files without any problem, but with `webpack` I got the error
> `Module not found: Error: Can't resolve 'fs/promises'`

I solved this. 

1. If you are using Electron and you want to use fs module in the renderer, add this object to the BrowserWindow instance settings:

```ts
new BrowserWindow({
        webPreferences: 
        {
            nodeIntegration: true
        }
    });
```
    
  2. If your issue is not related to frontend, then use the current way of importing fs module:
  ```ts
  import { promises as fs } from "fs";
  
  await fs.readFile()
  ```

**Comment by alexander-akait** [comment] 2021-04-12 10:54
> If you don't have anything good to say, better don't say anything because what you just said is not help either.

Don't be toxic, we ask you to create an example problem for a reason

It was fixed in webpack v5 (promises) without `as`, if you provide more information I can look

**Comment by angelhdz** [comment] 2021-04-13 20:13
> > If you don't have anything good to say, better don't say anything because what you just said is not help either.
> 
> Don't be toxic, we ask you to create an example problem for a reason
> 
> It was fixed in webpack v5 (promises) without `as`, if you provide more information I can look

**I AM THE ONE BEING TOXIC!?!?** Ha ha haha! Arrogant people always reflect on others and they love the word toxic only when they say it to others, but they never stop to think "wait, what If I am being toxic?" 

Bah. I rarely have to deal with people like you. Fortunately, there are more kind people in these places, so I will ignore you.

And thanks to other kind people (not like you), I found the solution to my issue and also contributed (I think?) to the original poster.

Thanks for nothing! https://github.com/alexander-akait

**Comment by alexander-akait** [comment] 2021-04-14 10:29
@angelhdz 

> I AM THE ONE BEING TOXIC!?!? Ha ha haha! Arrogant people always reflect on others and they love the word toxic only when they say it to others, but they never stop to think "wait, what If I am being toxic?"

I haven't told you a single harsh word, only ask about example of problem.

> Bah. I rarely have to deal with people like you. Fortunately, there are more kind people in these places, so I will ignore you.
> And thanks to other kind people (not like you), I found the solution to my issue and also contributed (I think?) to the original poster.

You have the right to do what you want.

Even more, you did not open this problem, did not provide any information, only shame me. How can I know your environment?

We ask developers to use the issue template to avoid unnecessary questions and help as quickly as possible. I apologize if I cannot help you.

**Comment by robo6633** [comment] 2022-10-16 15:06
> > > If you don't have anything good to say, better don't say anything because what you just said is not help either.
> > 
> > 
> > Don't be toxic, we ask you to create an example problem for a reason
> > It was fixed in webpack v5 (promises) without `as`, if you provide more information I can look
> 
> **I AM THE ONE BEING TOXIC!?!?** Ha ha haha! Arrogant people always reflect on others and they love the word toxic only when they say it to others, but they never stop to think "wait, what If I am being toxic?"
> 
> Bah. I rarely have to deal with people like you. Fortunately, there are more kind people in these places, so I will ignore you.
> 
> And thanks to other kind people (not like you), I found the solution to my issue and also contributed (I think?) to the original poster.
> 
> Thanks for nothing! https://github.com/alexander-akait

You shouldn't stress with people like him, he's clearly "too smart" to answer your question.

**Comment by angelhdzmultimedia** [comment] 2022-10-17 04:15
> > > > If you don't have anything good to say, better don't say anything because what you just said is not help either.
> > > 
> > > 
> > > Don't be toxic, we ask you to create an example problem for a reason
> > > It was fixed in webpack v5 (promises) without `as`, if you provide more information I can look
> > 
> > 
> > **I AM THE ONE BEING TOXIC!?!?** Ha ha haha! Arrogant people always reflect on others and they love the word toxic only when they say it to others, but they never stop to think "wait, what If I am being toxic?"
> > Bah. I rarely have to deal with people like you. Fortunately, there are more kind people in these places, so I will ignore you.
> > And thanks to other kind people (not like you), I found the solution to my issue and also contributed (I think?) to the original poster.
> > Thanks for nothing! https://github.com/alexander-akait
> 
> You shouldn't stress with people like him, he's clearly "too smart" to answer your question. The proof if that instead of helping people with their issues he just closes them down without even bother.

**Thanks mate. Many stuff have happened along the way after this heated thread.** ⏰

Of course, I've grown as a person. 📈 ✅

I learned not to engage in arguments with people, instead I smartly choose my battles. 🛡⚔🧠💡

Also, I switched to **Vite** and it has been heaven, not only the speed difference and configuration ease is dramatically superior, but the community is very helpful and very emphatic towards healthy conversations, and spreading awareness about the **Dunning Kruger Effect** that many maintainers in here suffer.

I spend all my time helping people for free on the internet, and when I open a ticket on Github, it's to help consumers of the library. Of course I also learn for my own projects (which are rare because I suffer of generalized anxiety and depression and I'm always procrastinating my projects), but in the end, the consumers of the library are the ones that are benefiting of the issues I open, so you can say I'm kind of a maintainer myself. I recently submitted my pull request for a library and got merged. My first contribution.

Recently I got another maintainer lecturing me about the rules of an open source project and I was like:
"Erm... I'm opening the issue... to help... the community... not to benefit myself..." and "So you mean that I first have to contribute on the source code of the library, so I can be able to open a ticket of a bug of the library!?".

They suddenly believe that because they are maintainers of the library, they can act like dictators and treat us the consumers however they feel like.

Also, you open a new issue, they hit you with the **"this is a duplicate"**. So you use your time and energy to find for an open/closed issue related to your issue instead, post a comment there, only to also get and attack for not providing a reproduction link, and not always the question/issue requires a reproduction link. Not always it's "an issue in our side".
Almost all the time is a bug or a missing/not-well-documented feature of the library. He didn't even took his time to make awareness of that fact, that instead of me opening a new issue, I searched for an existing one.

They also love to hit you with the frowned upon typical phrase "it wOrKs iN My mACHiNe" or "iT wOkS oN My sIDE".

And it's funny how nowadays they hide behind the "toxic" and "empathy" words, only when it benefits them.
For them, everyone who is defending from an arrogant/condescending reply are "toxic" and they themselves are the "victims" and they try to seek other people to back them up, like appealing to the people's need of being social justice warriors with a superior moral high ground.

Like "He bad, me good! Ooga, booga!".  

He didn't even have the decency of saying kind words (or leaving a kind reaction) after the fact that I provided a solution to this issue, instead of waiting to be fed with a solution,  something that not everyone does. 

So, you can't just win. Many inflated egos these days man. They try to get into your head and making you believe you are the problem, you are the toxic one, and all you are doing is defending yourself of arrogance/condescension attacks and exposing the truth.

But as I mentioned in this thread, I'm not gonna take it on so many kind and friendly maintainers/consumers 😊❤ I've had the honor to meet, for a few rotten apples. 🙄 

I just ignore them. 🥱

So, again, thank you for your supporting and encouraging words.  🤝🔥

For a world with more kindess and helpfulness and real empathy.

**Comment by AMohamedAakhil** [comment] 2024-08-17 10:55
yapper
