### ISSUE TITLE
Error in exiting from the options which appears on `npx webpack init`

### ISSUE THREAD

**Issue by gauravdas014** [webpack/webpack-cli#2233] opened 2020-12-11 17:12 UTC
**Describe the bug**
When I tried exiting from `npx webpack init` it showed some error. I was expecting a smooth exit, but it wasn't

**What is the current behavior?**
On exiting from the options on `npx webpack init` error is thrown

**To Reproduce**
`npx webpack init`
`ctrl + c` to exit

**Expected behavior**
The exit should be smooth with no error

**Screenshots**
![Screenshot (570)](https://user-images.githubusercontent.com/51530678/101933043-a2450c00-3c01-11eb-9314-e2e38e2abe51.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
     webpack: 5.10.0
    webpack-cli: 4.2.0

**Comment by alexander-akait** [comment] 2020-12-26 16:02
Can't reproduce, can you provide more info?

**Comment by anshumanv** [comment] 2021-02-06 13:46
Can't repro, closing, feel free to reopen and provide more info.

**Comment by alexander-akait** [comment] 2021-02-06 14:14
I think we need improve here, if you run `npm init` and press `ctrl + c` exit code will be 0, we should have the same behavior

**Comment by anshumanv** [comment] 2021-02-06 14:17
will look into it

**Comment by alexander-akait** [comment] 2021-02-15 17:17
Close in favor https://github.com/webpack/webpack-cli/issues/2430

**Closed by alexander-akait** 2021-02-15 17:17 UTC
Labels: Bug
