### ISSUE TITLE
Unable to use webpack-cli with @babel/core and babel-loader "^7.1.3"

### ISSUE THREAD

**Issue by esakkikrishnan** [webpack/webpack-cli#296] opened 2018-02-28 13:22 UTC
Unable to use  `webpack-cli` with `@babel/core` and `babel-loader "^7.1.3"`  and  since `webpack-cli` uses `jscodeshift` which intern uses `babel-register "^6.9.0"` and `babel-core "^6.26.0"` which is causing the following issue when used along with `@babel/core "^7.0.0-beta.40"` 

ISSUE: `Module build failed: TypeError: Cannot read property 'loose' of undefined (While processing preset: "/node_modules/@babel/preset-env/lib/index.js")`

Issue has been raised in the `@babel/core` but according this (https://github.com/babel/babel/issues/7110#issuecomment-354583771) it might be due to use of babel version 6 by some dependencies

using the following config

```json
// package.json

"dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-flow": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "babel-loader": "^7.1.3",
    "html-webpack-plugin": "webpack-contrib/html-webpack-plugin",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ]
  }
```
```
// webpack.config.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

// plugins
const HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: './src/index.html',
  filename: 'index.html',
  inject: 'body',
});

module.exports = {
  entry: {
    main: ['./src/index.js'],
    vendor: ['react', 'react-dom']
  },
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: '[name].js',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  plugins: [
    HtmlWebpackPluginConfig
  ],
  target: 'web'
};
```

**Comment by HJava** [comment] 2018-03-01 02:24
I have the same issue.
```json
{
  "name": "dxSDK",
  "dependencies": {
    "eventemitter3": "^3.0.1",
    "history": "^4.7.2",
    "immutable": "^3.8.2",
    "koa": "^2.5.0",
    "koa-router": "^7.4.0",
    "koa-static": "^3.0.0",
    "koa-views": "^6.1.4",
    "prop-types": "^15.6.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.7",
    "react-router": "^4.2.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "semver": "^5.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-export-default-from": "^7.0.0-beta.40",
    "@babel/polyfill": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "@babel/preset-stage-0": "^7.0.0-beta.40",
    "autoprefixer": "^6.7.7",
    "babel-loader": "^8.0.0-beta.2",
    "cache-loader": "^1.2.1",
    "css-loader": "^0.27.3",
    "happypack": "^4.0.1",
    "postcss-loader": "^1.3.3",
    "postcss-smart-import": "^0.6.10",
    "precss": "^1.4.0",
    "style-loader": "^0.14.1",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9",
    "webpack-dev-server": "^3.1.0"
  }
}
```

**Comment by ev1stensberg** [comment] 2018-03-01 14:19
This is quite unfortunate 👎 I'll check if there's something we can do

**Comment by ematipico** [comment] 2018-03-04 12:56
Babel 7 is still in beta! Shouldn't we wait a RC in order to start addressing issues? 

Once RC will be released there won't be any API changes and disruptions apart bug fixes. I'd suggest to lower the priority on this task.

**Comment by ev1stensberg** [comment] 2018-03-05 10:33
Maybe @hzoo has some input?

**Comment by hzoo** [comment] 2018-03-05 11:12
So via https://github.com/babel/babel-upgrade

```diff
"devDependencies": {
  "@babel/core": "7.0.0-beta.39",
+ "babel-core": "7.0.0-bridge.0",
  "jest": "^22.0.0"
},
"scripts": {
  "test": "jest"
}
```

the solution is to add a new dep on `"babel-core": "7.0.0-bridge.0",` which interally uses `@babel/core`. This is what is done for jest. It might still not work if the module itself isn't compatible with v7 though so would need some patches to jscodeshift.

**Comment by HJava** [comment] 2018-03-06 08:24
I try to install `babel-core`, but the problem isn't solved. It has the same logs.

**Comment by dmbfm** [comment] 2018-04-13 20:00
Adding `babel-core` bridge does not solve this. The problem is still present.

**Comment by ematipico** [comment] 2018-04-14 08:46
Thing is that `cli` doesn't have any dependency from Babel. It's a dep of a dep, `jscodeshift` if we want to be more specific. Now I wonder if this is an issue related to that library

**Comment by anlaakso** [comment] 2018-04-18 06:24
It seems that `yarn add babel-register@7.0.0-beta.3` or `npm install babel-register@7.0.0-beta.3` may help. At least it works for me.

**Comment by waxlamp** [comment] 2018-04-19 14:29
I just ran into this problem, but I solved it by also installing `@babel/register` as a dependency.

**Comment by HJava** [comment] 2018-04-20 13:49
I install `@babel/register` and solve the problem~~

**Comment by ematipico** [comment] 2018-04-20 15:50
@esakkikrishnan could you try to install `@babel/register` ?

**Closed** 2018-05-18 19:55 UTC
Labels: Priority: High, bug

**Comment by yekver** [comment] 2018-05-21 13:18
I fixed this problem with: `"babel-loader": "^8.0.0-beta"`

**Comment by Fandekasp** [comment] 2018-08-31 05:58
Having the issue 
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version
 of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the
stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to s
ee what is calling Babel.            
```
with all `@babel` packages at `^7.0.0` and `babel-loader@^8.0.0`

The traceback points to v8-compile-cache
```
    at Object.require.extensions.(anonymous function) [as .js] (/home/dori/Projects/work/miraidenshi/gounite/GOunite-xpc/node_modules/babel-register/lib/node.js:154:7)                                                  
    at Module.load (internal/modules/cjs/loader.js:599:32)                                                  
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                         
    at Module.require (internal/modules/cjs/loader.js:637:17)                                               
    at require (/home/dori/Projects/work/miraidenshi/gounite/GOunite-xpc/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/dori/Projects/work/miraidenshi/gounite/GOunite-xpc/node_modules/webpack-cli/bin/convert-argv.js:133:13)
```

and sure enough, it uses [babel 6.26.3](https://github.com/zertosh/v8-compile-cache/blob/master/package.json#L18).

**Comment by ev1stensberg** [comment] 2018-08-31 06:29
@Fandekasp most likely one of your dependencies are lower than 7

**Comment by Fandekasp** [comment] 2018-08-31 07:00
@ev1stensberg the traceback tells us that webpack-cli calls v8-compile-cache which requires babel 6, but you believe I have another unrelated package which, although not mentioned in the traceback is the cause for this issue.
This certainly makes debugging more difficult.

I used babel-upgrade to update my package.json, then went on to update some other packages as I fixed errors thrown out by webpack.

My current list of babel dependencies is as follow:
```
  "dependencies": {
    "@babel/runtime": "^7.0.0",
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-eslint": "9.0.0",
    "babel-jest": "23.4.2",
    "babel-loader": "^8.0.0",
    "babel-plugin-root-import": "^5.1.0",
    "babel-plugin-styled-components": "1.6.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-app": "3.1.2",
  }
```
I thought I went through the remaining babel-* packages to insure they were babel 7 compliant, but .. I'll check another time

**Comment by ematipico** [comment] 2018-08-31 08:51
If you believe to have issues between Babel versions, try to install this package

```bash
npm install -D babel-core@7.0.0-bridge.0
```

**Comment by Fandekasp** [comment] 2018-09-03 07:05
Unfortunately, I keep having this `The 'polyfill' option has been removed.` error.

**Comment by JamesTheHacker** [comment] 2018-09-08 15:00
The most common reason for this issue is having the wrong `babel-core` installed. For version 7 you need to use [@babel/core](https://www.npmjs.com/package/@babel/core) as opposed to [babe/core](https://www.npmjs.com/package/babel-core).

    npm uninstall babe-core
    npm install @babel/core

**Comment by Wkasel** [comment] 2018-12-07 06:56
I ran into the same issue, and my fix was to add `@babel/register`

Referenced from above link to other issue:
[https://github.com/babel/babel/issues/7110#issuecomment-372155709](https://github.com/babel/babel/issues/7110#issuecomment-372155709)

**Comment by vue-authenticate-larry12** [comment] 2025-10-20 17:27
I struggled with that problem and devised a remedy https://indefatigable-dbus.github.io/clojurescript-javascript/
