### ISSUE TITLE
webpack 5.1.3 [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning

### ISSUE THREAD

**Issue by vkings1** [webpack/webpack-cli#1966] opened 2020-10-17 18:20 UTC
![Screenshot from 2020-10-18 02-16-06](https://user-images.githubusercontent.com/22137536/96350435-68b3c100-10e8-11eb-99bf-7e59e0e4e8c2.png)

(node:31189) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
(node:31189) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:31189) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:31189) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_LENGTH] DeprecationWarning: chunk.files was changed from Array to Set (using Array property 'length' is deprecated)
(node:31189) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)

**Comment by bradtgmurray** [comment] 2020-10-18 17:00
Dupe of #1918 ?

**Comment by evilebottnawi** [comment] 2020-10-19 11:56
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Closed by evilebottnawi** 2020-10-19 11:56 UTC
Labels: Bug
