### ISSUE TITLE
webpack serve --open does not work?!

### ISSUE THREAD

**Issue by martinoppitz** [webpack/webpack-cli#2062] opened 2020-11-08 06:06 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snitin315** [comment] 2020-11-08 06:41
please use `webpack serve --open chrome`

**Comment by snitin315** [comment] 2020-11-08 06:42
`webpack serve --open` will be supported with `webpack-derv-server` version `4`

**Comment by snitin315** [comment] 2020-11-08 06:43
Duplicate of #2001

**Closed** 2020-11-08 06:44 UTC
Labels: Feature Request
