### ISSUE TITLE
TypeError: env.getArgument is not a function

### ISSUE THREAD

**Issue by luillyfe** [webpack/webpack-cli#301] opened 2018-03-01 19:39 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

Running this command: `webpack-cli init`,  it asks me a few quetions:

**Will your application have multiple bundles? (Y/n)**   n
**? Which module will be the first to enter the application? [example: './src/index']**  './src/index' (also I tried './src/index.js')
**? Which folder will your generated bundles be in? [default: dist]:** dist
**? Are you going to use this in production? (Y/n)**  n
**? Will you be using ES2015? (Y/n)** Y
**? Will you use one of the below CSS solutions?** No
**? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip)**
**? Name your 'webpack.[name].js?' [default: 'config']:** config 

It throws me this error:

```
/Users/luillyfe/WebstormProjects/configWebpack/node_modules/webpack-cli/lib/utils/modify-config-helper.js:34
                        env.getArgument("configuration")
                            ^

TypeError: env.getArgument is not a function
    at InitGenerator.env.run.on (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/webpack-cli/lib/utils/modify-config-helper.js:34:8)
    at emitNone (events.js:106:13)
    at InitGenerator.emit (events.js:208:7)
    at Queue.env.runLoop.once (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/webpack-fork-yeoman-generator/lib/index.js:381:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Queue.emit (events.js:208:7)
    at Queue.<anonymous> (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/queue.js:68:12)
    at Queue.next (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/queue.js:79:43)
    at SubQueue.run (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/subqueue.js:42:45)
    at Queue.next (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (/Users/luillyfe/WebstormProjects/configWebpack/node_modules/grouped-queue/lib/subqueue.js:42:45)

```
**What is the expected behavior?**
It should generate the `webpack.config.js` file 

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
this is how my my `package.json` file looks like:
```
"devDependencies": {
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9"
  },
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-preset-env": "^1.6.1",
    "lodash": "^4.17.5",
    "uglifyjs-webpack-plugin": "^1.2.2"
  }
```

**Comment by dhruvdutt** [comment] 2018-03-01 19:43
Duplicate of #291 

We've already identified the issue and resolving it. `webpack-cli` version `2.0.10` will be out soon with the fix.

**Comment by luillyfe** [comment] 2018-03-01 20:20
Awesome, Should I delete this one ?

**Comment by ev1stensberg** [comment] 2018-03-01 20:25
Yep, publishing eta 2h

**Closed by ev1stensberg** 2018-03-01 20:25 UTC

**Comment by dhruvdutt** [comment] 2018-03-02 07:25
[`2.0.10`](https://www.npmjs.com/package/webpack-cli) is out with the fix. :fire:

@luillyfe 
Please test and let us know if you still have any issues. :100:
